version: "3.8"
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/online_quiz
      - JWT_SECRET=your_jwt_secret_here
      - REFRESH_SECRET=your_refresh_secret_here
      - PORT=3000
    depends_on:
      - mongo

volumes:
  mongo-data:
